HOSTNAME = '127.0.0.1'
PORT     = '3306'
DATABASE = 'dachuang'
USERNAME = 'root'
PASSWORD = 'Hlt838292.'
DB_URI = 'mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8'.format(USERNAME,PASSWORD,HOSTNAME,PORT,DATABASE)

SQLALCHEMY_DATABASE_URI = DB_URI

SQLALCHEMY_TRACK_MODIFICATIONS = True

SECRET_KEY = "ssssadad123"



#  邮箱配置
MAIL_SERVER = "smtp.qq.com"
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_DEBUG = True
MAIL_USERNAME = "1872215235@qq.com"
MAIL_PASSWORD = "csumgwhwhezzcghe"
MAIL_DEFAULT_SENDER = "1872215235@qq.com"

# JWT设置

JWT_EXPIRY_HOURS = 128
JWT_REFRESH_DAYS = 3
JWT_SECRET = "123DSFHUIASHE235902384@@@aoisdj"



