"""empty message

Revision ID: 069d71caf694
Revises: a7536ebf8699
Create Date: 2022-10-03 14:37:40.045051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '069d71caf694'
down_revision = 'a7536ebf8699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendence', sa.Column('lesson_time', sa.String(length=50), nullable=False))
    op.drop_column('attendence', 'lessontime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendence', sa.Column('lessontime', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('attendence', 'lesson_time')
    # ### end Alembic commands ###
