"""empty message

Revision ID: 2ec30b1a6dab
Revises: 29271afb0bc0
Create Date: 2022-10-03 14:59:35.633893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ec30b1a6dab'
down_revision = '29271afb0bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendence', sa.Column('course_id', sa.Integer(), nullable=False))
    op.drop_column('attendence', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendence', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('attendence', 'course_id')
    # ### end Alembic commands ###
