"""empty message

Revision ID: 312f1bcf1bfe
Revises: d386be743749
Create Date: 2022-10-03 15:14:25.521581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '312f1bcf1bfe'
down_revision = 'd386be743749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendenceTable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('attendance_state', sa.String(length=50), nullable=False),
    sa.Column('attendance_time', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('lessons_time', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('attendence')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendence',
    sa.Column('attendance_state', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('attendance_time', mysql.DATETIME(), nullable=True),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lessons_time', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='attendence_ibfk_1'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('attendenceTable')
    # ### end Alembic commands ###
