"""empty message

Revision ID: 71d9e9e9e09c
Revises: 069d71caf694
Create Date: 2022-10-03 14:38:22.118694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '71d9e9e9e09c'
down_revision = '069d71caf694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendence', sa.Column('lessontime', sa.String(length=200), nullable=False))
    op.drop_column('attendence', 'lesson_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendence', sa.Column('lesson_time', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('attendence', 'lessontime')
    # ### end Alembic commands ###
