"""empty message

Revision ID: a7536ebf8699
Revises: f9ab36fa2a39
Create Date: 2022-10-03 14:37:06.298621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7536ebf8699'
down_revision = 'f9ab36fa2a39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendence', sa.Column('lessontime', sa.String(length=50), nullable=False))
    op.drop_column('attendence', 'lesson_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendence', sa.Column('lesson_time', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('attendence', 'lessontime')
    # ### end Alembic commands ###
