"""empty message

Revision ID: ae1a1950e38d
Revises: 312f1bcf1bfe
Create Date: 2022-10-03 15:54:26.540445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae1a1950e38d'
down_revision = '312f1bcf1bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendenceTable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('attendance_state', sa.String(length=50), nullable=False),
    sa.Column('attendance_time', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('lessons_time', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('attendencetable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendencetable',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('attendance_state', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('attendance_time', mysql.DATETIME(), nullable=True),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lessons_time', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name='attendencetable_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('attendenceTable')
    # ### end Alembic commands ###
