"""empty message

Revision ID: c872355e6575
Revises: 71d9e9e9e09c
Create Date: 2022-10-03 14:40:05.492347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c872355e6575'
down_revision = '71d9e9e9e09c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendence', sa.Column('lessons_time', sa.String(length=50), nullable=False))
    op.drop_column('attendence', 'lessontime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendence', sa.Column('lessontime', mysql.VARCHAR(length=200), nullable=False))
    op.drop_column('attendence', 'lessons_time')
    # ### end Alembic commands ###
